/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import Model.Item;
import config.SesionUsuario;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author adoili
 */
public class PanelLibro extends javax.swing.JPanel {

    private Model.Libro libroActual;

    public PanelLibro() {
        initComponents();

    }

    public PanelLibro(Model.Libro libro) {
        this.libroActual = libro;
        cargarDatosLibro();
        initComponents();

    }

    private void cargarDatosLibro() {
        if (libroActual != null) {
            LblNombreLibro.setText(libroActual.getTitulo());
            LblPrecio.setText(String.valueOf(libroActual.getPrecio()));
            LblDisponibildiad.setText(String.valueOf(libroActual.getStock()));
            try {
                String rutaImagen = "/img/" + libroActual.getTitulo().replace(" ", "") + ".jpg"; 

                ImageIcon icono = new ImageIcon(getClass().getResource(rutaImagen));
                if (icono.getImage() != null) {
                    Image img = icono.getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH);
                    lblImagen.setIcon(new ImageIcon(img));
                }
            } catch (Exception e) {
                lblImagen.setText("Sin imagen");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLasPruebasDelSol = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        LblNombreLibro = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        LblPrecio = new javax.swing.JLabel();
        LblDisponibildiad = new javax.swing.JLabel();
        BtnAgregarCarrito = new javax.swing.JButton();
        BtnDetallesLibro = new javax.swing.JButton();

        PanelLasPruebasDelSol.setBackground(new java.awt.Color(217, 202, 218));
        PanelLasPruebasDelSol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 196, 208), 2));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LasPruebasDelSol1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        LblNombreLibro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblNombreLibro.setText("Nombre libro");

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        LblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblPrecio.setText("$389");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel24Layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(LblPrecio)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel24Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LblPrecio)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        LblDisponibildiad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblDisponibildiad.setText("47 disponibles");

        BtnAgregarCarrito.setBackground(new java.awt.Color(101, 85, 143));
        BtnAgregarCarrito.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        BtnAgregarCarrito.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarCarrito.setText("AGREGAR AL CARRITO");
        BtnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarCarritoActionPerformed(evt);
            }
        });

        BtnDetallesLibro.setBackground(new java.awt.Color(101, 85, 143));
        BtnDetallesLibro.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        BtnDetallesLibro.setForeground(new java.awt.Color(255, 255, 255));
        BtnDetallesLibro.setText("DETALLES DEL LIBRO");
        BtnDetallesLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetallesLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLasPruebasDelSolLayout = new javax.swing.GroupLayout(PanelLasPruebasDelSol);
        PanelLasPruebasDelSol.setLayout(PanelLasPruebasDelSolLayout);
        PanelLasPruebasDelSolLayout.setHorizontalGroup(
            PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDisponibildiad, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLasPruebasDelSolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnAgregarCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDetallesLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        PanelLasPruebasDelSolLayout.setVerticalGroup(
            PanelLasPruebasDelSolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLasPruebasDelSolLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblDisponibildiad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAgregarCarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDetallesLibro)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLasPruebasDelSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLasPruebasDelSol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarCarritoActionPerformed
        if (libroActual != null) {
            JOptionPane.showMessageDialog(this, "Error: No hay libro seleccionado.");
            return;
        }
        List<Item> items = SesionUsuario.get().getCarrito().getItems();

        boolean encontrado = false;
        for (Item item : items) {
            if (item.getLibroId().equals(libroActual.getId())) {
                item.setCantidad(item.getCantidad() + 1);
                item.setSubtotal(item.getCantidad() * item.getPrecioUnitario());
                encontrado = true;
                break;
            }
        }
        if (!encontrado) {
            Item nuevoItem = new Item();
            nuevoItem.setLibroId(libroActual.getId());
            nuevoItem.setTitulo(libroActual.getTitulo());
            nuevoItem.setPrecioUnitario(libroActual.getPrecio());
            nuevoItem.setCantidad(1);
            nuevoItem.setSubtotal(libroActual.getPrecio());
            items.add(nuevoItem);
        }
        JOptionPane.showMessageDialog(this, "Libro agregado al carrito con exito!");

    }//GEN-LAST:event_BtnAgregarCarritoActionPerformed

    private void BtnDetallesLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetallesLibroActionPerformed

    }//GEN-LAST:event_BtnDetallesLibroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarCarrito;
    private javax.swing.JButton BtnDetallesLibro;
    private javax.swing.JLabel LblDisponibildiad;
    private javax.swing.JLabel LblNombreLibro;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JPanel PanelLasPruebasDelSol;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
